### PR TITLE
add installation guide to index page

### PR DESCRIPTION
**Pull request by bermannoah**

### CODE REVIEW

**Comment by antciccone** [comment]
this looks great 👍

**Comment by antciccone** [comment]
still looking great :)

**Comment by NickyBobby** [comment]
I agree with @antciccone, it looks 💯!!  Is it ready to be merged!? @bermannoah

**Comment by bermannoah** [comment]
Maybe!!! Keep commenting so I can keep testing my ability to pull mentions!

**Comment by NickyBobby** [comment]
Probably the best pull request I've ever seen!!! @bermannoah good job 👍

**Comment by NickyBobby** [comment]
And no conflicts with the base branch!?!? That's hot 🔥 🔥 🔥 🔥 !!!!

**Comment by NickyBobby** [comment]
Can you push up a merge conflict, @bermannoah ? I want to resolve it with the new github feature. k'thanks 😉

**Comment by bermannoah** [comment]
all I want for christmas is this PR to get merged

**Pull request merged**
